WebSchool2012023015/Web2012023015School/src/Web2012023015School/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Web2012023015School.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Web2012023015School.Controllers
{
    public class PageController : BaseController
    {
        // GET: /<controller>/
        [FromServices]
        public ArticleContext DB { get; set; }
        [HttpGet]
        public IActionResult News()
        {
            return PagedView(DB.News, 7);
        }
        
        [HttpGet]
        public IActionResult Article()
        {
            return PagedView(DB.Article, 7);
        }
        
        [HttpGet]
        public IActionResult Inform()
        {
            return PagedView(DB.Inform, 7);
        }

        [HttpGet]
        public IActionResult Photos()
        {
            return PagedView(DB.Photos, 7);
        }

        [HttpGet]    
        public IActionResult RecruitStudents()
        {
            return PagedView(DB.RecruitStudents, 7);
        }

       
    }
}

WebSchool2012023015/Web2012023015School/src/Web2012023015School/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>学校后台管理</title>
    <link href="~/styles/style.css" type="text/css" rel="stylesheet" />
    <link href="~/styles/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
</head>
<body>
        <nav class="nav navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="nav nav-pills">
                    <li class="active"><a asp-action="Manage" asp-controller="Home">后台首页</a></li>
                    <li><a asp-action="Index" asp-controller="Home" target="_blank">网站首页</a></li>
                    <li>
                        <ul class="nav nav-pills">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">新闻管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsNews" asp-controller="Admin">管理新闻</a></li>
                                    <li><a asp-action="CreateNews" asp-controller="Admin">添加新闻</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">文章管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsArticle" asp-controller="Admin">管理文章</a></li>
                                    <li><a asp-action="CreateArticle" asp-controller="Admin">添加文章 </a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">通知公告管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsInform" asp-controller="Admin">管理通知公告</a></li>
                                    <li><a asp-action="CreateInform" asp-controller="Admin">添加通知公告 </a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">校园风光管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsPhotos" asp-controller="Admin">管理校园风光</a></li>
                                    <li><a asp-action="CreatePhotos" asp-controller="Admin">添加校园风光</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">招生信息管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsRecruitStudents" asp-controller="Admin">管理招生信息</a></li>
                                    <li><a asp-action="CreateRecruitStudents" asp-controller="Admin">添加招生信息</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">学校信息管理<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-action="DetailsSchoolInfo" asp-controller="Admin">管理学校信息</a></li>
                                    <li><a asp-action="CreateSchoolInfo" asp-controller="Admin">添加学校信息</a></li>
                                </ul>
                            </li>

                        </ul>
                    </li>
                    <li><a asp-action="Modify" asp-controller="Account">修改密码</a></li>
                    <li><a asp-action="Login" asp-controller="Account">退出后台</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="height:40px;"></div>
    <div class="container">
        <div class="col-md-12">
            <div class="Layout-content">
                <div class="Layout-content-wrap">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <img src="~/images/xiang.gif" />
    </div>
</body>
</html>

WebSchool2012023015/Web2012023015School/src/Web2012023015School/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>贵港市达开实验小学</title>

    <!-- Bootstrap core CSS -->
    <link href="~/styles/bootstrap.min.css" rel="stylesheet">
    <link href="~/styles/ie10-viewport-bug-workaround.css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/ie-emulation-modes-warning.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Custom styles for this template -->
    <link href="~/styles/carousel.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-action="Index" asp-controller="Home"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-action="Index" asp-controller="Home">首页</a></li>
                    <li><a asp-action="Details" asp-controller="Home">学校概况</a></li>
                    <li><a asp-action="Photos" asp-controller="Page">校园风光</a></li>
                    <li><a asp-action="News" asp-controller="Page">校园新闻</a></li>
                    <li><a asp-action="Article" asp-controller="Page">师生文章</a></li>
                    <li><a asp-action="RecruitStudents" asp-controller="Page">招生信息</a></li>
                    <li><a asp-action="Inform" asp-controller="Page">通知公告</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">友情链接 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="http://ggdksy.ggedu.gov.cn" target="_blank">达开初中</a></li>
                            <li><a href="http://ggdkgz.ggedu.gov.cn" target="_blank">达开高中</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">著名高校</li>
                            <li><a href="http://www.tsinghua.edu.cn" target="_blank">清华大学</a></li>
                            <li><a href="http://www.pku.edu.cn" target="_blank">北京大学</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="col-md-3" style="float:right;margin-right:5px;">
        <!--教育资源 start-->

        <div class="panel panel-default">
            <div class="panel-heading ">
                教育资源
                <a href="#" class="text-muted pull-right" style="text-decoration:none;">更多>></a>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.eol.cn/" style="text-decoration:none;">中国教育在线</a></strong>
                <p>中国最大的教育门户</p>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://cai.7cxk.net/Index.html" style="text-decoration:none;">中小学课件站</a></strong>
                <p>中小学课件免费下载的好地方</p>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.tongyi.com/" style="text-decoration:none;">中国统一教育网</a></strong>
                <p>教育从心开始</p>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.51edu.com/xiaoxue/" style="text-decoration:none;">小学教育网</a></strong>
                <p>小学教育精品学习网</p>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.xj5u.com/" style="text-decoration:none;">小学资源网</a></strong>
                <p>全面的小学资源任你搜索</p>
            </div>
        </div>

        <!--教育资源 end-->

        <!--中考 start-->

        <div class="panel panel-default">
            <div class="panel-heading">
                直击中考
                <a href="#" class="text-muted pull-right" style="text-decoration:none;">更多>></a>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.liuxue86.com/zhongkao/" style="text-decoration:none;">中考网</a></strong>
                <p>2016中考网是国内最大的中考门户网站,为广大考生提供:2016中考成绩查询、中考分数线、中考时间、中考报名、中考满分作文、中考试题答案等2016年中考最新资讯...</p>
            </div>
            <div class="panel-body">
                <strong class="panel-title"><a target="_blank" href="http://www.zk5u.com/" style="text-decoration:none;">中考资源网</a></strong>
                <p>中考资源网,是一家专业为中考提供教学资源服务的网站,网站拥有中考试题,试卷,学案,课件等教学资源80多万套,内涵 初中九大学科,40多个版本备课资料,每日更新中考教学...</p>
             </div>
        </div>

        <!--中考 end-->

        <!--推荐新闻 start-->

        <div class="panel panel-default">
            <div class="panel-heading">
                网校联谊
                <a href="#" class="text-muted pull-right" style="text-decoration:none;">更多>></a>
            </div>
            <div class="list-group-item" style="border:0;">
                <h3 class="panel-title">
                    <a target="_blank" href="http://30edu.com/" class="text-muted" style="text-decoration:none;">30网校</a>
                </h3>
                    <p>30网校-->为您的孩子打造一片天地。</p>
                
            </div>
            <div class="list-group-item" style="border:0;">
                <a target="_blank" href="http://vk.30edu.com/OnlineCourse.aspx" class="text-muted" style="text-decoration:none;">网校微课</a>
                <p>网校微-->课助孩子成长</p>
            </div>
            <div class="list-group-item" style="border:0;">
                <a target="_blank" href="http://www.wenku1.com/" class="text-muted" style="text-decoration:none;">第一文库网</a>
                <p>第一文库-->搜集更多资讯</p>
            </div>
            <div class="list-group-item" style="border:0;">
                <a target="_blank" href="http://jc.30dao.com/Default.html" class="text-muted" style="text-decoration:none;">书道网</a>
                <p>书道网-->轻轻松松练好字</p>
            </div>
</div>

        <!--推荐新闻 end-->

        <a href="#" class="btn btn-info btn-sm">
            <span class="glyphicon glyphicon-arrow-up"></span> 
        </a>
    </div>
    <div class="container-fluid">
        <div>
            @RenderBody()
        </div>
    </div> 
    <!-- FOOTER -->
    <footer class="text-center">
        <img src="~/images/xiang.gif" />
        <p>&copy;CopyRight By 2012023015. &middot;<a asp-action="Login" asp-controller="Account">后台登陆管理</a></p>
    </footer>
</body>
</html>